config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'pages#home'
  root to: 'animations#index'
    resources :animations do
      resources :bookings, only: [ :show, :new, :create ]
      resources :reviews, only: [ :new, :create ]
    end
    resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animation.rb
class Animation < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :reviews, dependent: :destroy

  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
  validates :category, presence: true
  validates :price, presence: true, numericality: { only_interger: true }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  CATEGORIES = ['Clown', 'Dwarf', 'Mermaid', 'Llama', 'Monkey', 'Chicken', 'Stripper', 'Juggler', 'Singer', 'Magician']
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :animation
  belongs_to :user

  validates :place, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :animation
  belongs_to :user

  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :animations, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animations_controller.rb
class AnimationsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :set_animation, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = " \
        animations.title ILIKE :query \
        OR animations.description ILIKE :query \
      "
      @animations = policy_scope(Animation).where(sql_query, query: "%#{params[:query]}%")
    else
      @animations = policy_scope(Animation)
    end
  end

  def show
    @booking = Booking.new
    @review = Review.new

    @markers =
      {
        lng: @animation.longitude,
        lat: @animation.latitude
      }
  end

  def new
    @animation = Animation.new
    authorize @animation
  end

  def create
    @animation = current_user.animations.new(animation_params)
    authorize @animation
    if @animation.save
      redirect_to animation_path(@animation)
    else
      render :new
    end
  end

  def edit
    @animation = Animation.find(params[:id])
  end

  def update
    animation = Animation.find(params[:id])
    animation.update(animation_params)
    redirect_to animation_path(animation)
  end

  def destroy
    animation = Animation.find(params[:id])
    animation.destroy
    redirect_to animations_path
  end

  private

  def animation_params
    params.require(:animation).permit(:title, :category, :price, :photo, :address, :description)
  end

  def set_animation
    @animation = Animation.find(params[:id])
    authorize @animation
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: :show
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
  # For additional fields in app/views/devise/registrations/new.html.erb
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # For additional in app/views/devise/registrations/edit.html.erb
  devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @bookings = Booking.all
    authorize @bookings
  end

  def new
    @booking = Booking.new
    authorize @booking
    @animation = Animation.find(params[:animation_id])
  end

  def create
    @animation = Animation.find(params[:animation_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    authorize @booking
    @booking.animation = @animation
    if @booking.save
      redirect_to user_path(current_user), notice: "\u{1F4C5} Your booking request has been sent \u{1F4C5}"
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:animation_id, :place, :arrival_time, :departure_time)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    authorize @review
    @animation = Animation.find(params[:animation_id])
  end

  def create
    @animation = Animation.find(params[:animation_id])
    @review = Review.new(review_params)
    authorize @review
    @review.animation = @animation
    @review.user = current_user
    if @review.save
      redirect_to animation_path(@animation)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animations/_card.html.erb
<div class="wrapper" id="results">
    <div class="container">
      <div class="row">
        <% animations.each do |animation| %>
          <% if animation.photo.blank? %>
            <div class="col-xs-12 col-sm-6 col-md-4 centered" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dydwtoubz/image/upload/v1550242925/cj6ntnbniqzqhjqmeldu.jpg)">
              <div class="card">
                <div class="card-description text-center">
                  <h3><%= link_to animation.title.titleize, animation_path(animation) %></h3>
                  <%= link_to animation.category.titleize, animation_path(animation) %>
                </div>
                <div class="card-ratings">
                <% if animation.reviews.empty? %>
                  <p>No rating</p>
                <% else %>
                  <% animation.reviews.first.rating.to_i.times do  %>
                   <i class="fas fa-star fa-sm"></i>
                  <% end %>
                <% end %>
                </div>
                <i class="far fa-heart" id="biglove"></i>
              </div>

            </div>
          <% else %>
            <div class="col-xs-12 col-sm-6 col-md-4 centered" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
             url('<%= cl_image_path animation.photo, height: 300, width: 400, crop: :fill %>')">
             <div class="card text-center">
                <div class="card-description text-center"><%= link_to animation.title.titleize, animation_path(animation) %>
                </div>
                <div class="card-description text-center"><%= link_to animation.category.titleize, animation_path(animation) %>
                </div>
                <div class="card-ratings">
                <% if animation.reviews.empty? %>
                  <p>No rating</p>
                <% else %>
                  <% animation.reviews.first.rating.to_i.times do  %>
                   <i class="fas fa-star fa-sm"></i>
                  <% end %>
                <% end %>
              </div>
                <i class="far fa-heart" id="biglove"></i>
             </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="row text-center">
        <%= link_to "Add your animation", new_animation_path, class: "btn btn-medium ", id: "new_animation_button"%>
      </div>
    </div>
  </div>

app/views/animations/edit.html.erb
<div class="wrapper-form" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dydwtoubz/image/upload/v1550844293/balloons-birthday-bright-796606.jpg)">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h2>Add your animation</h2>
      <%= simple_form_for(@animation) do |f| %>
        <%= f.input :title, placeholder: 'Enter your title' %>
        <%= f.input :category, collection: Animation::CATEGORIES, as: :select %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :photo %>

        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: "btn btn-medium" %>
      <% end %>
      </div>
  </div>
</div>

app/views/animations/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dydwtoubz/image/upload/v1550771298/bachelorama/celebration-colorful-colourful-1684187.jpg)">
    <div class="banner-content">
      <h1>Bachelorama</h1>
      <h2>Odd & Fun rentals for your Bachelor/ette Party</h2>
    </div>
</div>

<%= render 'card', animations: @animations %>

app/views/animations/new.html.erb
<div class="wrapper-form" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dydwtoubz/image/upload/v1550844293/balloons-birthday-bright-796606.jpg)">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h2> &#x1F389;  Add your animation! &#x1F389; </h2>
      <%= simple_form_for(@animation) do |f| %>
        <%= f.input :title, placeholder: 'Enter your title' %>
        <%= f.input :category, collection: Animation::CATEGORIES, as: :select %>
        <%= f.input :description, placeholder: 'What makes you special?' %>
        <%= f.input :address, placeholder: 'Gimme your address' %>
        <%= f.input :price, placeholder: 'Show me the money' %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <hr>
        <%= f.submit class: "btn-medium"%>
        <%= link_to "Back", animations_path, class: 'btn btn-medium' %>
      <% end %>
      </div>
  </div>
</div>

app/views/animations/show.html.erb
<% if @animation.photo.blank? %>
  <div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dydwtoubz/image/upload/v1550242925/cj6ntnbniqzqhjqmeldu.jpg)">
    <h1><%= @animation.title %></h1>
  </div>
<% else %>
  <div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @animation.photo %>')">
    <h1><%= @animation.title %></h1>
  </div>
<% end %>
<div class="main-container-show">
  <div class="wrapper-show">
    <div class="row-show">
      <h2 id= "category-title" style= "color: #ea825e" ><%= @animation.category.capitalize %></h2>
      <div class="grid">
          <div class="description">
            <h4>Description</h4>
            <p><%= @animation.description %></p>
          </div>
          <div class="calendar">

            <%= simple_form_for [@animation, @booking],  html: {class: 'flexbox'} do |f| %>
              <%= f.input :arrival_time, as: :string, required: false, input_html: { class: 'datepickershow margin-right start_date'} %>
              <%= f.input :departure_time, as: :string, required: false, input_html: { class: 'datepickershow end_date' } %>
            <% end %>

          </div>
        <div class="detail">
          <h2 style= "color: black"> <%= @animation.price %> $ </h2>
          <hr>
          <div class="links">
            <ul class= "ul-show">
              <li>
                <%= link_to "Book", new_animation_booking_path(@animation), class: 'btn btn-medium'%>
              </li>
              <hr>
              <li>
                <%= link_to "Review", new_animation_review_path(@animation), class: 'btn btn-medium', id: "showbutton"   %>
            </li>
              <%= link_to "Back", animations_path, class: 'btn btn-medium', id: "showbutton" %>
              <li>
            </li>
              <li>
              <% if @animation.user == current_user %>
              <%= link_to "Edit", edit_animation_path, class: 'btn btn-medium' %>
              <%= link_to "Delete", animation_path(@animation.id),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: 'btn btn-medium' %>
              <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="reviews">
      <h3 id= "review-title" >Reviews</h3>
      <% @animation.reviews.each do |review| %>
        <div class="message">
          <img class="avatar-large" src="">
          <div class="message-name">
            <ul style="list-style: none;">
              <li>
                <h3 color: #ea825e =>Frank</h3>
              </li>
              <li>
                <h3 style= "color: #ea825e" =>22/02/19</h3>
              </li>
            </ul>
          </div>
          <div class="message-body">
            <p style= "color: #ea825e" =><%= review.content  %></p>
          </div>
          <div class="message-rate">
            <h4 style= "color: #ea825e" ><%= review.rating  %></h4>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>
<!-- fix the new animation booking -->
<!-- Fix the review comment, comments are not showing -->

app/views/bookings/new.html.erb
<div class="wrapper-form" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dydwtoubz/image/upload/v1550844293/balloons-birthday-bright-796606.jpg)">
  <div class="row" style="height: 79vh">
    <div class="col-md-6 col-md-offset-3" style="margin-top: 55px">
      <h1 class="title">You're booking: <%= @animation.title %></h1>
        <%= simple_form_for [@animation, @booking] do |f| %>
        <%= f.input :place, label: "Where is the party at?", placeholder: "Your city"%>
        <%= f.input :arrival_time, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :departure_time, as: :string, required: false, input_html: {class: "datepicker"} %>
        <hr>
        <%= f.submit "Book now", class: 'btn btn-medium' %>
        <%= link_to "Back", animation_path(@animation), class: 'btn btn-medium' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
    <title>BACHELORAMA</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://kitt.lewagon.com/placeholder/cities/berlin');">
  <div class="banner-content">
    <h1>Le Wagon Berlin</h1>
    <p>Learn to code with us in Berlin</p>
    <a class="btn btn-primary btn-lg">Start now</a>
  </div>
</div>

app/views/pages/_card.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Le Wagon Shanghai</h2>
          <p>Very cool city, the best</p>
        </div>
        <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
        <a class="card-link" href="#" ></a>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h2>coucou</h2>

app/views/reviews/new.html.erb
<div class="wrapper-form" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dydwtoubz/image/upload/v1550844293/balloons-birthday-bright-796606.jpg)">
  <div class="row" style="height: 80vh">
    <div class="col-md-6 col-md-offset-3">
      <h2>Add a review</h2>
      <%= simple_form_for [@animation, @review] do |f| %>
        <%= f.input :rating , collection: 0..5 %>
        <%= f.input :content %>
        <hr>
        <%= f.submit class: "btn btn-medium"%>
        <%= link_to "Back", animation_path(@animation), class: 'btn btn-medium' %>
      <% end %>
      </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer was proudly CTRL-C/V from Le Wagon <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag 'https://res.cloudinary.com/dydwtoubz/image/upload/v1550841868/confetti.png' %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <div class="container-searchbar">
      <%= form_tag animations_path, id: 'search-form',method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "searchbar",
          placeholder: "Find animations"
        %>
        <img src="https://images-na.ssl-images-amazon.com/images/I/41gYkruZM2L.png" alt="Magnifying Glass" class="button">
      <% end %>
    </div>

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Add animation", new_animation_path, class: "navbar-wagon-item navbar-wagon-link"%>
      <%= link_to "Bookings", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag 'https://res.cloudinary.com/dydwtoubz/image/upload/v1550846737/jules-the-pink-lama.png', class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <div class="booking-list">
    <h2>Welcome, <%= @user.name %>:</h2>
    <h3>Upcoming plans:</h3>

    <ul class="list-unstyled">
      <ul class="list-unstyled" id="booked-header">
        <li>Animation:</li>
        <li>Starts at:</li>
        <li>Ends at:</li>
        <li>Local:</li>
        <li>Status:</li>
      </ul>
      <% @user.bookings.each do |booking| %>
        <li class="booked">

          <div class="booked-upvote text-center">
            <p>ab</p>
          </div>

          <img src=<%= booking.animation.photo %> alt="" class="booked-image img-rounded" style="height: 300, width: 400">

          <div class="booked-description">
            <p><%= booking.animation.title %></p>
            <p><%= booking.arrival_time.strftime('%d/%m/%Y') %></p>
            <p><%= booking.departure_time.strftime('%d/%m/%Y') %></p>
            <p><%= booking.place %></p>
          </div>


          <div class="status">
            <p>Pending</p>
          </div>
        </li>
        <% end %>
    </ul>
  </div>
</div>